export const ACTION_TYPE = {
    //LOGIN
    LOGIN_START: "LOGIN_START",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_FAIL: "LOGIN_FAIL",

    LOGOUT_START: "LOGOUT_START",
    LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
    LOGOUT_FAIL: "LOGOUT_FAIL",

    //REGISTER
    REGISTER_START: "REGISTER_START",
    REGISTER_SUCCESS: "REGISTER_SUCCESS",
    REGISTER_FAIL: "REGISTER_FAIL",

    //USER INFO
    GET_USER_INFO_START: "GET_USER_INFO_START",
    GET_USER_INFO_SUCCESS: "GET_USER_INFO_SUCCESS",
    GET_USER_INFO_FAIL: "GET_USER_INFO_FAIL",

    UPDATE_USER_INFO_START: "UPDATE_USER_INFO_START",
    UPDATE_USER_INFO_SUCCESS: "UPDATE_USER_INFO_SUCCESS",
    UPDATE_USER_INFO_FAIL: "UPDATE_USER_INFO_FAIL",

    CREATE_USER_INFO_START: "CREATE_USER_INFO_START",
    CREATE_USER_INFO_SUCCESS: "CREATE_USER_INFO_SUCCESS",
    CREATE_USER_INFO_FAIL: "CREATE_USER_INFO_FAIL",

    //USER INFO
    GET_USER_INFO_START: "GET_USER_INFO_START",
    GET_USER_INFO_SUCCESS: "GET_USER_INFO_SUCCESS",
    GET_USER_INFO_FAIL: "GET_USER_INFO_FAIL",

    UPDATE_USER_INFO_START: "UPDATE_USER_INFO_START",
    UPDATE_USER_INFO_SUCCESS: "UPDATE_USER_INFO_SUCCESS",
    UPDATE_USER_INFO_FAIL: "UPDATE_USER_INFO_FAIL",

    UPDATE_USER_IMAGE_START: "UPDATE_USER_IMAGE_START",
    UPDATE_USER_IMAGE_SUCCESS: "UPDATE_USER_IMAGE_SUCCESS",
    UPDATE_USER_IMAGE_FAIL: "UPDATE_USER_IMAGE_FAIL",

    CREATE_USER_INFO_START: "CREATE_USER_INFO_START",
    CREATE_USER_INFO_SUCCESS: "CREATE_USER_INFO_SUCCESS",
    CREATE_USER_INFO_FAIL: "CREATE_USER_INFO_FAIL",
    
        
    GET_OFFICE_LIST_START:"GET_OFFICE_LIST_START",
    GET_OFFICE_LIST_SUCCESS:"GET_OFFICE_LIST_SUCCESS",
    GET_OFFICE_LIST_FAIL:"GET_OFFICE_LIST_FAIL",

    GET_CATEGORY_START:"GET_CATEGORY_START",
    GET_CATEGORY_SUCCESS:"GET_CATEGORY_SUCCESS",
    GET_CATEGORY_FAIL:"GET_CATEGORY_FAIL",

    BOOKING_START:"BOOKING_START",
    BOOKING_SUCCESS:"BOOKING_SUCCESS",
    BOOKING_FAIL:"BOOKING_FAIL",

    BOOKING_HISTORY_START:"BOOKING_HISTORY_START",
    BOOKING_HISTORY_SUCCESS:"BOOKING_HISTORY_SUCCESS",
    BOOKING_HISTORY_FAIL:"BOOKING_HISTORY_FAIL",
}
